### ISSUE TITLE
NPWP

### ISSUE THREAD

**Issue by jasonjb82** [rasyidstat/nusantr#1]
Hi Pak Rasyid, 

I am currently working on a project that looks at the oil palm industry in Indonesia and the sustainability issues surrounding it. I really like your package and it will be extremely useful for me in some of my tasks on this project. One really useful dataset that would nice to have in your package in NPWP info on companies. I believe there is a database out there but it will be nice to be able to query that directly through an R package. Not sure if that's possible but just thought I'd put it out there.

Thanks again for all your effort on this package and keep up the good work!

Best,
Jason

**Comment by rasyidstat** [comment]
Hi Pak Jason,

Thank you for the suggestion. Unfortunately, NPWP data is not publicly available. Maybe you can request it directly to Indonesia ministry of finance (Kemenkeu).

**Comment by jasonjb82** [comment]
Thanks for the suggestion Pak Rasyid! Much appreciated
