### ISSUE TITLE
Export data transjakarta

### ISSUE THREAD

**Issue by masardisaja** [rasyidstat/nusantr#2]
Halo pak Rasyid,
Mohon info bagaimana cara export data transjakarta ke csv? Saya coba write.csv dan write.table selalu error.

> write.csv(transjakarta, "C:/Temp/transjakarta_halte.csv")
Error in write.table(transjakarta, "C:/Temp/transjakarta_halte.csv", col.names = NA,  : 
  unimplemented type 'list' in 'EncodeElement'

Terima kasih

**Comment by rasyidstat** [comment]
Hai,
Hal tersebut terjadi karena di dalam datanya ada variabel yg berbentuk list, yaitu variabel `schedule_id`
Gunakan `select(transjakarta, -schedule_id)` untuk membuang variabel tersebut
